### ISSUE TITLE
How can I run this ?

### ISSUE THREAD

**Issue by leovarmak** [paralin/Dota2LobbyDump#3]

**Comment by paralin** [comment]
It's a code example, not really a finished program. I don't provide any support for it.

It's just a standard C# program, you can run it with visual studio 2015 or similar.

**Comment by leovarmak** [comment]
I would like to contact you once. Can I get some messenger id ?

**Comment by paralin** [comment]
Sorry, I can't provide support for this past GitHub issues, and I can't provide any for this particular repository
